#apiVersion: v1
#kind: ResourceQuota
#metadata:
#  name: ecommerce-quota
#  namespace: ecommerce
#spec:
#  hard:
#    requests.cpu: "1600m"
#    requests.memory: 8Gi
#    limits.cpu: "3500m"
#    limits.memory: 20Gi

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 5Gi
    limits.cpu: "5"
    limits.memory: 10Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: moni-limitrange
  namespace: monitoring
spec:
  limits:
  - type: Container
    max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "100m"
      memory: "1Gi"
    maxLimitRequestRatio:
      cpu: "10"

  

# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: argocd-quota
#   namespace: argocd
# spec:
#   hard:
#     requests.cpu: "0.1"
#     requests.memory: 0.6Gi
#     limits.cpu: "0.3"
#     limits.memory: 1Gi
  
